name: main

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: PHP CS Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff --dry-run

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli-alpine
    services:
      mercure:
        image: dunglas/mercure
        env:
          #ADDR: :80
          JWT_KEY: '!ChangeMe!'
          DEMO: 1
          ALLOW_ANONYMOUS: 1
          CORS_ALLOWED_ORIGINS: '*'
          PUBLISH_ALLOWED_ORIGINS: http://mercure
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_password
          MYSQL_DATABASE: db_name
          MYSQL_ROOT_PASSWORD: root
        #ports:
          #- 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Set Up Container
      run: |
        # https://docs.pact.io/docker#reference-image
        apk add --no-cache --virtual build-dependencies build-base
        apk --no-cache add ca-certificates wget bash \
          && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
          && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk \
          && apk add glibc-2.29-r0.apk
        wget https://get.symfony.com/cli/installer -O - | bash -s -- --install-dir=/usr/bin
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
        composer global require hirak/prestissimo > /dev/null
        apk add --no-cache $PHPIZE_DEPS
        docker-php-ext-install pdo_mysql

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: composer install

    - name: Start Server
      run: |
        echo "DATABASE_URL=mysql://db_user:db_password@mysql:3306/db_name?serverVersion=5.7" > .env.local
        php bin/console doctrine:schema:create
        php bin/console hautelook:fixtures:load
        symfony serve --daemon

    - name: Test
      run: |
        ./vendor/bin/codecept build
        ./vendor/bin/codecept run
      env:
        PACT_BROKER_URI: ${{ secrets.PACT_BROKER_URI }}
        PACT_BROKER_BEARER_TOKEN: ${{ secrets.PACT_BROKER_BEARER_TOKEN }}
