name: main

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: PHP CS Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff --dry-run

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli-alpine
    steps:
    - name: Set Up Container
      run: |
        apk add --no-cache bash
        wget https://get.symfony.com/cli/installer -O - | bash -s -- --install-dir=/usr/bin
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
        composer global require hirak/prestissimo > /dev/null

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Dependencies
      run: composer install

    - name: Test
      run: |
        symfony serve --daemon
        ./vendor/bin/codecept build
        ./vendor/bin/codecept run
      env:
        PACT_BROKER_URI: ${{ secrets.PACT_BROKER_URI }}
        PACT_BROKER_BEARER_TOKEN: ${{ secrets.PACT_BROKER_BEARER_TOKEN }}
